[package]
name = "ok"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version="3.0.0", features= ["derive"]}
failure = "0.1.5"
shellexpand = "2.1.0"
colored = "2.0.0"
