[package]
name = "ok"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0" 
failure = "0.1.5"
shellexpand = "1.0.0"
colored = "1.7.0"
git2 = "0.8.0"
